/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationIndexRouteImport } from './routes/reservation/index'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIndexRoute = ReservationIndexRouteImport.update({
  id: '/reservation/',
  path: '/reservation/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/': typeof EventsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/reservation/': typeof ReservationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/items': typeof ItemsIndexRoute
  '/reservation': typeof ReservationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/': typeof EventsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/reservation/': typeof ReservationIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/'
    | '/gallery/'
    | '/items/'
    | '/reservation/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events' | '/gallery' | '/items' | '/reservation' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/events/'
    | '/gallery/'
    | '/items/'
    | '/reservation/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
  ReservationIndexRoute: typeof ReservationIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/': {
      id: '/reservation/'
      path: '/reservation'
      fullPath: '/reservation/'
      preLoaderRoute: typeof ReservationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
  ReservationIndexRoute: ReservationIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
